# utils/constants.py

PREGNANCY_WEEKS = {
    1: "Your baby is the size of a poppy seed 🌱",
    2: "Your baby is the size of a sesame seed",
    3: "Your baby is the size of a pin head",
    4: "Your baby is the size of a sweet pea 🌿",
    5: "Your baby is the size of an apple seed 🍎",
    6: "Your baby is the size of a lentil",
    7: "Your baby is the size of a blueberry 🫐",
    8: "Your baby is the size of a raspberry",
    9: "Your baby is the size of a cherry 🍒",
    10: "Your baby is the size of a strawberry 🍓",
    11: "Your baby is the size of a fig",
    12: "Your baby is the size of a lime 🍋",
    13: "Your baby is the size of a pea pod",
    14: "Your baby is the size of a lemon 🍋",
    15: "Your baby is the size of an apple 🍏",
    16: "Your baby is the size of an avocado 🥑",
    17: "Your baby is the size of a pear 🍐",
    18: "Your baby is the size of a sweet potato 🍠",
    19: "Your baby is the size of a mango 🥭",
    20: "Your baby is the size of a banana 🍌",
    21: "Your baby is the size of a carrot 🥕",
    22: "Your baby is the size of a papaya",
    23: "Your baby is the size of a grapefruit",
    24: "Your baby is the size of an ear of corn 🌽",
    25: "Your baby is the size of a cauliflower",
    26: "Your baby is the size of a lettuce head 🥬",
    27: "Your baby is the size of a head of broccoli 🥦",
    28: "Your baby is the size of an eggplant 🍆",
    29: "Your baby is the size of a butternut squash",
    30: "Your baby is the size of a cabbage 🥬",
    31: "Your baby is the size of a coconut 🥥",
    32: "Your baby is the size of a squash",
    33: "Your baby is the size of a pineapple 🍍",
    34: "Your baby is the size of a cantaloupe 🍈",
    35: "Your baby is the size of a honeydew melon",
    36: "Your baby is the size of a head of romaine lettuce",
    37: "Your baby is the size of a winter melon",
    38: "Your baby is the size of a leek",
    39: "Your baby is the size of a small watermelon 🍉",
    40: "Your baby is the size of a watermelon 🍉 — almost here!",
}

NUTRITION_TIPS = {
    "first_trimester": [
        "Focus on folate-rich foods (leafy greens, fortified cereals)",
        "Increase protein intake (lean meats, beans, eggs)",
        "Stay hydrated — aim for 8–10 glasses of water daily",
        "Take prenatal vitamins with folic acid",
    ],
    "second_trimester": [
        "Add calcium-rich foods (dairy, almonds, tofu)",
        "Include iron-rich foods (spinach, red meat, lentils)",
        "Eat plenty of colourful fruits and vegetables",
        "Increase caloric intake by ~300 calories/day",
    ],
    "third_trimester": [
        "Increase caloric intake by ~450 calories/day",
        "Focus on omega-3 fatty acids (salmon, walnuts, flaxseed)",
        "Eat frequent small meals to manage heartburn",
        "Stay hydrated to reduce swelling",
    ],
}

EXERCISE_RECOMMENDATIONS = {
    "first_trimester": [
        "Walking (30 min/day)",
        "Swimming & water aerobics",
        "Prenatal yoga",
        "Light strength training",
    ],
    "second_trimester": [
        "Low-impact aerobics",
        "Stationary cycling",
        "Modified strength training",
        "Prenatal Pilates",
    ],
    "third_trimester": [
        "Gentle stretching & flexibility",
        "Walking at comfortable pace",
        "Pelvic floor exercises (Kegels)",
        "Deep breathing & relaxation",
    ],
}